services:

  db:
    image: postgres:15
    container_name: mentions-graph-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mention_graph_db
    ports:
      - "5432:5432"
    volumes:
      - mentions-graph-db-data:/var/lib/postgresql/data
    networks:
      - mentions-graph-net

  redis:
    image: redis:latest
    container_name: mentions-graph-redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes", "--appendfsync", "everysec" ]
    networks:
      - mentions-graph-net

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mentions-graph-app
    ports:
      - "8000:8000"
    env_file: "./backend/.env"
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
    networks:
      - mentions-graph-net

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: "./backend/.env"
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
      - app
    command: celery -A app.celery_app worker --loglevel=info --queues mentions --concurrency=4
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - mentions-graph-net
volumes:
  mentions-graph-db-data:


networks:
  mentions-graph-net:
    driver: bridge
