"""migration

Revision ID: 01e7a9086575
Revises: 
Create Date: 2025-07-28 06:24:32.820636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01e7a9086575'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_id'), 'nodes', ['id'], unique=False)
    op.create_index(op.f('ix_nodes_username'), 'nodes', ['username'], unique=True)
    op.create_table('edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'target_id', name='uq_source_target')
    )
    op.create_index(op.f('ix_edges_id'), 'edges', ['id'], unique=False)
    op.create_index(op.f('ix_edges_source_id'), 'edges', ['source_id'], unique=False)
    op.create_index(op.f('ix_edges_target_id'), 'edges', ['target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_edges_target_id'), table_name='edges')
    op.drop_index(op.f('ix_edges_source_id'), table_name='edges')
    op.drop_index(op.f('ix_edges_id'), table_name='edges')
    op.drop_table('edges')
    op.drop_index(op.f('ix_nodes_username'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_id'), table_name='nodes')
    op.drop_table('nodes')
    # ### end Alembic commands ###
